#!/bin/bash



# Configurations
SOURCE_DIR="/home/user/mydata"       # Directory to back up
BACKUP_NAME="backup_$(date +%Y%m%d_%H%M%S).tar.gz"
DEST_DIR="/backups"                  # Destination directory on remote
REMOTE_USER="username"
REMOTE_HOST="192.168.1.100"          # Change to your remote server IP/hostname
LOG_FILE="/tmp/backup_report.log"


# Create backup archive
echo "Creating backup..."
tar -czf /tmp/$BACKUP_NAME $SOURCE_DIR
if [ $? -ne 0 ]; then
    echo " Backup creation failed!" | tee -a $LOG_FILE
    exit 1
fi


# Transfer backup to remote server
echo "Transferring backup to remote server..."
scp /tmp/$BACKUP_NAME ${REMOTE_USER}@${REMOTE_HOST}:${DEST_DIR}
if [ $? -ne 0 ]; then
    echo " Backup transfer failed!" | tee -a $LOG_FILE
    exit 1
fi


# Report success
echo " Backup successful: $BACKUP_NAME" | tee -a $LOG_FILE
