#!/bin/bash


# Thresholds
CPU_THRESHOLD=80
MEM_THRESHOLD=80
DISK_THRESHOLD=80

# CPU usage
CPU=$(top -bn1 | grep "Cpu(s)" | awk '{print 100 - $8}')
CPU=${CPU%.*}

# Memory usage
MEM=$(free | grep Mem | awk '{print $3/$2 * 100.0}')
MEM=${MEM%.*}

# Disk usage
DISK=$(df -h / | awk 'NR==2 {print $5}' | sed 's/%//')


echo "CPU Usage: ${CPU}%"
echo "Memory Usage: ${MEM}%"
echo "Disk Usage: ${DISK}%"

# Alerts
if [ "$CPU" -gt "$CPU_THRESHOLD" ]; then
    echo "ALERT: CPU usage is high!"
fi

if [ "$MEM" -gt "$MEM_THRESHOLD" ]; then
    echo "ALERT: Memory usage is high!"
fi

if [ "$DISK" -gt "$DISK_THRESHOLD" ]; then
    echo "ALERT: Disk usage is high!"
fi
